"""add_few_shot_actor_owner_quality_score

Revision ID: 1c18dee24218
Revises: 18664d2b15a5
Create Date: 2026-04-18 15:03:37.674729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c18dee24218'
down_revision: Union[str, Sequence[str], None] = '18664d2b15a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment_runs', sa.Column('quality_score', sa.Integer(), nullable=True))
    op.add_column('experiments', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('prompt_audit', sa.Column('actor', sa.String(), nullable=True))
    op.add_column('prompt_versions', sa.Column('few_shot_examples', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_versions', 'few_shot_examples')
    op.drop_column('prompt_audit', 'actor')
    op.drop_column('experiments', 'owner')
    op.drop_column('experiment_runs', 'quality_score')
    # ### end Alembic commands ###
